
slack:
  webhook-url:
    info: https://hooks.slack.com/services/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
    warn: https://hooks.slack.com/services/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
    error: https://hooks.slack.com/services/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