
slack:
  webhook-url:
    info: https://hooks.slack.com/services/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
    warn: https://hooks.slack.com/services/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
    error: https://hooks.slack.com/services/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